### ISSUE TITLE
Wrong header used for original_mail to

### ISSUE THREAD

**Issue by saghaulor** [livebg/bounce_email#9]
@mitio I mixed up some of the headers. I've already fixed it. Additionally, I'm implementing extracting the original_mail to from VERP.

I'm debating extracting some of this behavior into its own class so that we can implement tests for these private methods.

I'm just opening this issue so that you don't push another version just yet.

**Comment by saghaulor** [comment]
@mitio in reply to https://github.com/livebg/bounce_email/pull/8#issuecomment-91574874: It's my understanding per http://en.wikipedia.org/wiki/Variable_envelope_return_path#With_VERP that the recipient address is embedded inside of the return path. As such, we can attempt to divine the recipient address using a regex that follows the recommended format. If you review some of the bounced mails, for example https://github.com/livebg/bounce_email/blob/master/test/bounces/tt_1234175799.txt#L3, the ones that contain the 'X-Original-To' header are following the VERP convention, which is to say, the header contains the original recipient.

**Comment by mitio** [comment]
@saghaulor I see.

I've [implemented VERP in the smailer gem](https://github.com/livebg/smailer/blob/master/lib/smailer/tasks/process_bounces.rb) using a bounce address of the following type: `bounces-KEY@bounces.example.com`. The key is not the sender's email, but just a random hash, as I wanted to be sure that I do not confuse the remote mail server with complicated return paths. I wanted to be sure that I'll get the bounce at the catch all email.

My point here is that the format which includes the original recipient in the reply-to header of VERP is not a hard rule, it's just a suggested format. To be honest, I have no statistical data of how widely used this format of return path in VERP is. If it's used a lot, it might make sense to implement it, but I have doubts. This is too vauge of a format and it'd be a bit risky to make the assumption of the format. I'd rather not put this logic into the gem and instead leave it up to the users of the gem to extract the original recipient the way they want. I think we've made reasonable efforts to do that for them already, including your recent work.

**Comment by saghaulor** [comment]
@mitio fair enough. I'll just fix the incorrect header issue and leave out the VERP logic.
